[versions]
kotlin = "2.4.10"
agp = "9.3.1"
core-ktx = "1.19.0"
appcompat = "1.7.1"
material = "1.14.0"
constraintlayout = "2.2.2"
talsec-freerasp = "19.2.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
talsec-freerasp = { module = "com.aheaditec.talsec.security:TalsecSecurity-Community", version.ref = "talsec-freerasp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[bundles]
androidx = ["core-ktx", "appcompat", "material", "constraintlayout"]