plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "com.aheaditec.talsec.demoapp"

    defaultConfig {
        applicationId "com.aheaditec.talsec.demoapp"
        minSdkVersion 23
        compileSdkVersion 36
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // freeRASP SDK
    implementation libs.talsec.security
    implementation libs.kotlin.stdlib
    implementation libs.bundles.androidx
}