pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp" }
        maven { url 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/common' }
    }
}

include ':app'
rootProject.name = "FreeRASPDemoApp"